server:
  port: 8189
  servlet:
    context-path: /spring
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=spring_shopv2
    username: postgres
    password: 12345
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  postgresql:
    console:
      enabled: true
  flyway:
    baseline-on-migrate: true